services:
  - type: web
    name: erpnext-web
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: docker/Dockerfile
    entrypoint: ./docker/entrypoint.sh
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: your_mysql_root_password
      - key: PORT
        value: 8000  # Required by Render, your app will use $PORT internally

  - type: pserv
    name: mariadb
    plan: starter
    env: docker
    repo: https://github.com/render-examples/mariadb
    dockerfilePath: Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: your_mysql_root_password
