services:
  - type: web
    name: erpnext-web
    env: docker
    plan: starter
    region: oregon
    dockerfilePath: Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: amee8386
      - key: PORT
        value: "8000"
      - key: DB_HOST
        value: db.onrender.com

  - type: pserv
    name: db
    plan: starter
    env: docker
    repo: https://github.com/render-examples/mariadb.git
    dockerfilePath: Dockerfile
    envVars:
      - key: MYSQL_ROOT_PASSWORD
        value: amee8386
